# Generated by Django 5.1.3 on 2024-11-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UDVogueApp', '0004_remove_editorial_contacto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='revista',
            name='imagen',
            field=models.ImageField(null=True, upload_to='revistas/'),
        ),
    ]
